import { defineField, defineType } from 'sanity'

export default defineType({
  name: 'sobre',
  title: 'Página Sobre',
  type: 'document',

  groups: [
    { name: 'hero',         title: '1 — Hero' },
    { name: 'origem',       title: '2 — A Origem' },
    { name: 'proposito',    title: '3 — O Propósito' },
    { name: 'diferenciais', title: '4 — Diferenciais' },
    { name: 'zeElias',      title: '5 — Zé Elias' },
    { name: 'cursos',       title: '6 — Os Cursos' },
    { name: 'pedro',        title: '7 — Pedro / Bio' },
    { name: 'cta',          title: '8 — CTA Final' },
  ],

  fields: [

    // ── ABA 1: HERO ──────────────────────────────────────────
    defineField({
      name: 'subtitulo',
      title: 'Label (acima do título)',
      type: 'string',
      group: 'hero',
      description: 'Texto pequeno exibido acima do título principal.',
      initialValue: 'A nossa história',
    }),
    defineField({
      name: 'titulo',
      title: 'Título principal (H1)',
      type: 'string',
      group: 'hero',
      initialValue: 'A Eco Guitar nasceu numa caçamba.',
    }),
    defineField({
      name: 'heroSubtitulo',
      title: 'Subtítulo',
      type: 'text',
      rows: 3,
      group: 'hero',
      initialValue: 'Uma madeira que ia para o lixo. Uma ideia que não largou. E a convicção de que instrumentos brasileiros, feitos com madeira brasileira, têm uma história para contar.',
    }),
    defineField({
      name: 'heroImagem',
      title: 'Imagem de fundo',
      type: 'image',
      group: 'hero',
      description: 'Imagem de fundo exibida no topo da página. Use uma foto do ateliê ou dos instrumentos.',
      options: { hotspot: true },
    }),

    // ── ABA 2: A ORIGEM ──────────────────────────────────────
    defineField({
      name: 'origemLabel',
      title: 'Label',
      type: 'string',
      group: 'origem',
      initialValue: 'Como tudo começou',
    }),
    defineField({
      name: 'origemTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'origem',
      initialValue: 'Pedro voltava a pé do trabalho. E não parava de olhar para as caçambas.',
    }),
    defineField({
      name: 'origemParagrafo1',
      title: 'Parágrafo 1',
      type: 'text',
      rows: 4,
      group: 'origem',
      initialValue: 'No Higienópolis, obras de reforma descartavam madeira boa. Peroba, jatobá, peças de demolição que iriam para o lixo. Pedro trabalhava numa produtora e aprendia lutheria no Projeto Guri com um professor que logo viria a falecer. Continuou sozinho, na oficina, com o que tinha aprendido.',
    }),
    defineField({
      name: 'origemParagrafo2',
      title: 'Parágrafo 2',
      type: 'text',
      rows: 4,
      group: 'origem',
      initialValue: 'A primeira guitarra que construiu usou madeira resgatada da rua. Não foi uma estratégia de posicionamento — foi uma percepção: material de qualidade sendo desperdiçado, e a certeza de que cada peça poderia guardar uma história diferente.',
    }),
    defineField({
      name: 'origemParagrafo3',
      title: 'Parágrafo 3',
      type: 'text',
      rows: 2,
      group: 'origem',
      initialValue: 'Em 2014, essa percepção virou a Eco Guitar.',
    }),
    defineField({
      name: 'origemFoto',
      title: 'Foto (aparece ao lado do texto)',
      type: 'image',
      group: 'origem',
      description: 'Foto do Pedro trabalhando na oficina ou imagem das madeiras. Opcional — sem foto, o texto ocupa a largura toda.',
      options: { hotspot: true },
    }),

    // ── ABA 3: O PROPÓSITO ───────────────────────────────────
    defineField({
      name: 'propositoLabel',
      title: 'Label',
      type: 'string',
      group: 'proposito',
      initialValue: 'Por que existimos',
    }),
    defineField({
      name: 'propositoTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'proposito',
      initialValue: 'Continuar o ciclo. Dar nova vida ao que ia para o lixo.',
    }),
    defineField({
      name: 'propositoParagrafo1',
      title: 'Parágrafo 1',
      type: 'text',
      rows: 3,
      group: 'proposito',
      initialValue: 'A Eco Guitar nasceu com uma premissa clara: instrumentos musicais não precisam vir de madeiras importadas, e bom material não precisa ser descartado.',
    }),
    defineField({
      name: 'propositoParagrafo2',
      title: 'Parágrafo 2',
      type: 'text',
      rows: 4,
      group: 'proposito',
      initialValue: 'Usamos madeiras brasileiras — de demolição e de reflorestamento — não como alternativa de custo, mas como escolha deliberada. A madeira que veio de uma reforma carrega décadas de história antes de virar instrumento. Isso não é desvantagem — é o que nos diferencia.',
    }),
    defineField({
      name: 'propositoCitacao',
      title: 'Citação em destaque',
      type: 'text',
      rows: 3,
      group: 'proposito',
      description: 'Frase exibida em bloco visual de destaque com borda turquesa.',
      initialValue: 'Queremos desmistificar a crença de que só as madeiras estrangeiras são boas para a fabricação de instrumentos musicais.',
    }),
    defineField({
      name: 'propositoParagrafo3',
      title: 'Parágrafo final',
      type: 'text',
      rows: 3,
      group: 'proposito',
      initialValue: 'E quando a madeira traz história — a da casa que foi demolida, a da família do aluno — o instrumento deixa de ser um objeto e vira uma herança.',
    }),

    // ── ABA 4: DIFERENCIAIS ──────────────────────────────────
    defineField({
      name: 'diferenciaisLabel',
      title: 'Label',
      type: 'string',
      group: 'diferenciais',
      initialValue: 'O que nos torna únicos',
    }),
    defineField({
      name: 'diferenciaisTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'diferenciais',
      initialValue: 'Três coisas que você não vai encontrar em outro lugar.',
    }),
    defineField({
      name: 'diferenciais',
      title: 'Cards de diferenciais',
      type: 'array',
      group: 'diferenciais',
      description: 'Máximo 3 cards. Cada um tem ícone (emoji), título e texto.',
      validation: (Rule) => Rule.max(3),
      of: [
        {
          type: 'object',
          name: 'diferencialItem',
          fields: [
            defineField({ name: 'icone',  title: 'Ícone (emoji)', type: 'string' }),
            defineField({ name: 'titulo', title: 'Título',        type: 'string' }),
            defineField({ name: 'texto',  title: 'Texto',         type: 'text', rows: 3 }),
          ],
          preview: { select: { title: 'titulo', subtitle: 'icone' } },
        },
      ],
    }),

    // ── ABA 5: ZÉ ELIAS ─────────────────────────────────────
    defineField({
      name: 'zeEliasLabel',
      title: 'Label',
      type: 'string',
      group: 'zeElias',
      initialValue: 'Instrumento com história',
    }),
    defineField({
      name: 'zeEliasTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'zeElias',
      initialValue: 'Zé Elias trouxe a madeira do avô.',
    }),
    defineField({
      name: 'zeEliasParagrafo1',
      title: 'Parágrafo 1 — Quem é Zé Elias',
      type: 'text',
      rows: 4,
      group: 'zeElias',
      initialValue: "Zé Elias é um dos maiores ídolos da história do Corinthians. O 'Zé da Fiel' ganhou a Copa do Brasil em 1995, levou o bronze nas Olimpíadas de Atlanta em 1996, e foi campeão da Copa da UEFA pela Inter de Milão em 1998 — jogando ao lado de Ronaldo, Zanetti e Simeone. Tricampeão grego pelo Olympiakos, campeão brasileiro pelo Santos. Hoje, comentarista da ESPN Brasil.",
    }),
    defineField({
      name: 'zeEliasParagrafo2',
      title: 'Parágrafo 2 — A história',
      type: 'text',
      rows: 4,
      group: 'zeElias',
      initialValue: 'Quando decidiu construir sua própria guitarra, Zé Elias não foi a uma loja. Foi até a Eco Guitar — e chegou com um pedaço de madeira retirado da casa do avô. Quis que aquela madeira fizesse parte da sua Les Paul. Não era uma questão técnica. Era uma questão de memória.',
    }),
    defineField({
      name: 'zeEliasParagrafo3',
      title: 'Parágrafo 3 — Conclusão',
      type: 'text',
      rows: 3,
      group: 'zeElias',
      initialValue: 'Pedro construiu o instrumento com essa madeira. E foi exatamente o tipo de encomenda que justifica a existência da Eco Guitar: não apenas fazer uma guitarra, mas guardar uma história dentro dela.',
    }),
    defineField({
      name: 'zeEliasCitacao',
      title: 'Citação em destaque',
      type: 'text',
      rows: 2,
      group: 'zeElias',
      initialValue: 'Desde trás da própria madeira, a gente traz a história da família.',
    }),
    defineField({
      name: 'zeEliasCitacaoAutor',
      title: 'Autor da citação',
      type: 'string',
      group: 'zeElias',
      initialValue: 'Pedro Machado, 2019',
    }),
    defineField({
      name: 'zeEliasVideoId',
      title: 'ID do vídeo YouTube',
      type: 'string',
      group: 'zeElias',
      description: 'Apenas o ID (ex: KJ6HKJSFWm8). Não cole a URL completa.',
      initialValue: 'KJ6HKJSFWm8',
    }),
    defineField({
      name: 'zeEliasFoto',
      title: 'Foto da guitarra / do processo',
      type: 'image',
      group: 'zeElias',
      description: 'Foto da Les Paul finalizada ou de uma etapa da construção. Aparece ao lado do texto.',
      options: { hotspot: true },
    }),

    // ── ABA 6: OS CURSOS ─────────────────────────────────────
    defineField({
      name: 'cursosLabel',
      title: 'Label',
      type: 'string',
      group: 'cursos',
      initialValue: 'Os cursos',
    }),
    defineField({
      name: 'cursosTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'cursos',
      initialValue: 'Começou no susto. Evoluiu com método.',
    }),
    defineField({
      name: 'cursosParagrafo1',
      title: 'Parágrafo 1',
      type: 'text',
      rows: 4,
      group: 'cursos',
      initialValue: 'Um ano e meio depois de começar, Pedro recebeu um telefonema de Renato, de Brasília. Queria fazer um curso. Pedro disse que não tinha estrutura ainda, nem método desenvolvido. Renato disse que estava bem assim — e marcou para a semana seguinte.',
    }),
    defineField({
      name: 'cursosParagrafo2',
      title: 'Parágrafo 2',
      type: 'text',
      rows: 4,
      group: 'cursos',
      initialValue: 'Em uma semana, o primeiro curso aconteceu. Desde então, a Eco Guitar vem investindo e refinando o método — com turmas de até 4 pessoas, do Express ao Extensivo, para quem quer aprender uma etapa específica ou construir o instrumento completo do zero.',
    }),

    // ── ABA 7: PEDRO / BIO ───────────────────────────────────
    defineField({
      name: 'pedroLabel',
      title: 'Label',
      type: 'string',
      group: 'pedro',
      initialValue: 'O luthier',
    }),
    defineField({
      name: 'pedroTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'pedro',
      initialValue: 'Conheça Pedro Machado',
    }),
    defineField({
      name: 'bio',
      title: 'Bio (texto longo)',
      type: 'array',
      of: [{ type: 'block' }],
      group: 'pedro',
      description: 'Texto editável com formatação. Aparece ao lado da foto.',
    }),
    defineField({
      name: 'fotoPrincipal',
      title: 'Foto do Pedro',
      type: 'image',
      group: 'pedro',
      description: 'Retrato do Pedro Machado. Aparece ao lado da bio.',
      options: { hotspot: true },
    }),
    defineField({
      name: 'curiosidadesLabel',
      title: 'Label — Fatos rápidos',
      type: 'string',
      group: 'pedro',
      initialValue: 'Fatos rápidos',
    }),
    defineField({
      name: 'curiosidadesTitulo',
      title: 'Título — Fatos rápidos (H2)',
      type: 'string',
      group: 'pedro',
      initialValue: 'Um pouco sobre Pedro',
    }),
    defineField({
      name: 'curiosidades',
      title: 'Curiosidades / Fatos rápidos',
      type: 'array',
      group: 'pedro',
      description: 'Cards com fatos sobre o Pedro. Ícone (emoji) + texto.',
      of: [
        {
          type: 'object',
          fields: [
            defineField({ name: 'icone', title: 'Ícone (emoji)', type: 'string' }),
            defineField({ name: 'texto', title: 'Texto', type: 'string' }),
          ],
          preview: { select: { title: 'texto', subtitle: 'icone' } },
        },
      ],
    }),
    defineField({
      name: 'fotosAtelier',
      title: 'Galeria do Ateliê',
      type: 'array',
      group: 'pedro',
      description: 'Fotos do ateliê exibidas em grade após a bio. Máximo 6 fotos.',
      validation: (Rule) => Rule.max(6),
      of: [{ type: 'image', options: { hotspot: true } }],
    }),

    // ── ABA 8: CTA FINAL ─────────────────────────────────────
    defineField({
      name: 'ctaLabel',
      title: 'Label',
      type: 'string',
      group: 'cta',
      initialValue: 'Venha nos conhecer',
    }),
    defineField({
      name: 'ctaTitulo',
      title: 'Título (H2)',
      type: 'string',
      group: 'cta',
      initialValue: 'O ateliê fica na Vila Leopoldina, em São Paulo.',
    }),
    defineField({
      name: 'ctaTexto',
      title: 'Texto',
      type: 'text',
      rows: 2,
      group: 'cta',
      initialValue: 'Trazendo o seu instrumento para regulagem, ou vindo descobrir os cursos — você é bem-vindo.',
    }),
    defineField({
      name: 'ctaBotaoTexto',
      title: 'Texto do botão',
      type: 'string',
      group: 'cta',
      initialValue: 'Falar com Pedro',
    }),

  ],
})
